---
install:
- yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
- sudo apt-get update
- sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra
script: make
after_success: .utility/update-gh-pages.sh
env:
  global:
  - secure: ! 'V3QpWZhgho1I+2NM55TVKaN0I+tqUAFj2Dn64k5drtOyxIkaC1rn1I83sMJM

      BpZ/4LUDmg/RyX442J0PmFkPYHhOdjk6rO+3M37kR5QBb3rFsfM+92cRAX+8

      rehnFFyeamwIs3W1669k6vHQS7HUCQMFNsj7D6EQoCYfbvkGGFs='
