env:
  global:
    - secure: "HlfHUJEBCx7ypvFJH1kVggCbo3pxVIsbcbexLRbJMnkn33OTIwemfMylrRYO\n7T99E0ZJWW5Te1Owd4CgagXNTJRwo4aOFLcguasQf3oQJ3qjlFwAP8TyEMdP\nlCl78KdC7r7rYAkjTS/42MmV7y8pLKGSq+9K64kGhP0DjnduSBc="

install:
  - yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-lang-cyrillic

script: make

#after_success: .utility/update-gh-pages.sh
