env:
  global:
    - secure: "OeNZfNu1C/H1wUbqAWJ4UhZmDC+mtl51OliONbbX5kyk1gwlOZ42TfzXW1WF\nUiMPthHw8ZKYpb9XJ+gZkxtJ8xMcOLIkxlw/jGHlrmH30sMcKrPMT/tZg3qP\n6jRZNy7qiwpnsQHd/JdhREXuSRul+VPk0YCnQLDpeNfjx9RcNSk="

install:
  - yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra

script: make

after_success: .utility/update-gh-pages.sh
